# Experiment Parameters
epochs: 1000
iters_per_checkpoint: 100
seed: 1234
dynamic_loss_scaling: true
fp16_run: false
distributed_run: false
dist_backend: "nccl"
dist_url: "tcp://localhost:54321"
cudnn_enabled: true
cudnn_benchmark: false
ignore_layers: 

# Data Parameters
load_mel_from_disk: false
data_dir: data
training_files: 'metadata.csv'
validation_files: 'metadata.csv'
text_cleaners: 
audio_path_column_name: audio
text_column_name: text

# Audio Parameters
n_fft: 2048
n_stft: ??? # Will be set in code
frame_shift: 0.0125
hop_length: ??? # Will be set in code
frame_length: 0.05
filter_length: 1024
win_length: ??? # Will be set in code
mel_freq: 128
max_mel_time: 800
max_db: 100
mel_fmax: 8000.0
mel_fmin: 0.0
scale_db: 10
ref: 4.0
power: 2.0
norm_db: 10
ampl_multiplier: 10.0
ampl_amin: 1e-10
db_multiplier: 1.0
ampl_ref: 1.0
sample_rate: 22050
ampl_power: 1.0
n_mel_channels: 120
max_wav_value: 1.0 #experiment on this

# Model Parameters
n_symbols: 768 # This needs to be set dynamically based on len(symbols)
symbols_embedding_dim: 512

# Encoder parameters
encoder_kernel_size: 5
encoder_n_convolutions: 3
encoder_embedding_dim: 512
decoder_attention_heads: 8
encoder_n_layers: 6
encoder_attention_heads: 8
embedding_size: 512
text_num_embeddings: 768

# Decoder parameters
n_frames_per_step: 1  # currently only 1 is supported
decoder_rnn_dim: 1024
prenet_dim: 256
max_decoder_steps: 1000
gate_threshold: 0.5
p_attention_dropout: 0.1
p_decoder_dropout: 0.1

# Attention parameters
attention_rnn_dim: 1024
attention_dim: 256

# Location Layer parameters
attention_location_n_filters: 128
attention_location_kernel_size: 31

# Mel-post processing network parameters
postnet_embedding_dim: 512
postnet_kernel_size: 5
postnet_n_convolutions: 5

# Optimization Hyperparameters
use_saved_learning_rate: false
learning_rate: 1e-4
weight_decay: 1e-5
grad_clip_thresh: 1.0
batch_size: 64
lr_gamma: 0.95
mask_padding: true  # set model's padded outputs to padded values